"""
ChipForge Tuning Temperaments
==============================
Historical and microtonal tuning systems beyond 12-tone equal temperament.

Why this matters: Bach wrote for well temperament (Werckmeister), Mozart's
strings played in modified meantone, medieval music used Pythagorean tuning,
and harmonic singing groups use just intonation. Each system gives certain
keys a unique character ("key colour") that equal temperament smooths flat.

All functions are pure: given a MIDI note, a key center, and a temperament,
they return a frequency in Hz. The mixer/synth never need to know which
system is in use — they just receive a frequency.

Tuning systems implemented:
  - "equal"        — 12-TET (modern standard, every semitone = 2^(1/12))
  - "just"         — 5-limit just intonation (pure ratios from a tonic)
  - "pythagorean"  — Stacked perfect fifths (3:2), one wolf fifth
  - "meantone"     — 1/4-comma meantone (Renaissance/early Baroque)
  - "werckmeister" — Werckmeister III (well temperament, J.S. Bach era)
  - "kirnberger"   — Kirnberger III (well temperament, late Baroque)
"""

from __future__ import annotations

from typing import Literal

Temperament = Literal[
    "equal", "just", "pythagorean", "meantone", "werckmeister", "kirnberger",
]

# Reference: A4 = 440 Hz in equal temperament. We compute every other note as
# a ratio multiplier away from the tonic in cents, then convert to Hz.

# All tables below are CENTS above C (the "natural" tuning anchor of each
# historical system). 1200 cents = 1 octave. 100 cents = 1 equal-temp semitone.

# 12-TET reference (every semitone is exactly 100 cents).
_EQUAL_CENTS: list[float] = [i * 100.0 for i in range(12)]

# 5-limit just intonation built from C as tonic.
# Ratios → cents via 1200 * log2(ratio).
# These are the "pure" intervals that beat-free choirs sing.
_JUST_RATIOS: list[float] = [
    1.0,        # C   unison
    16/15,      # C#  diatonic semitone
    9/8,        # D   major second
    6/5,        # D#  minor third
    5/4,        # E   major third
    4/3,        # F   perfect fourth
    45/32,      # F#  augmented fourth
    3/2,        # G   perfect fifth
    8/5,        # G#  minor sixth
    5/3,        # A   major sixth
    9/5,        # A#  minor seventh
    15/8,       # B   major seventh
]

# Pythagorean tuning: build all 12 notes by stacking 3:2 fifths from C.
# Wolf interval lands between G# and Eb. Bright leading tones, harsh thirds.
# Generated by going 6 fifths up and 5 down from C, then octave-reducing.
# The result (rounded to 4 dp in cents) is well-known historically:
_PYTHAGOREAN_CENTS: list[float] = [
    0.0,        # C
    113.685,    # C#  (apotome above C)
    203.910,    # D   (9/8)
    315.641,    # D#  (32/27 minor third)
    407.820,    # E   (81/64 ditone — bright!)
    498.045,    # F   (4/3)
    611.730,    # F#  (729/512 tritone)
    701.955,    # G   (3/2 — pure)
    815.640,    # G#  (128/81)
    905.865,    # A   (27/16)
    1019.550,   # A#  (16/9)
    1109.775,   # B   (243/128)
]

# 1/4-comma meantone: tempers each fifth flat by 1/4 of the syntonic comma so
# major thirds become pure (5:4). Used roughly 1500-1700. Beautiful in keys
# near C; the "wolf" fifth between G# and Eb is wildly out of tune.
# Standard table (cents above C):
_MEANTONE_CENTS: list[float] = [
    0.0,        # C
    76.049,     # C#  (chromatic semitone)
    193.157,    # D
    310.265,    # D#  / Eb
    386.314,    # E   — pure 5:4
    503.422,    # F
    579.471,    # F#
    696.578,    # G   (tempered fifth)
    772.627,    # G#
    889.735,    # A
    1006.843,   # A#  / Bb
    1082.892,   # B
]

# Werckmeister III (1691): well temperament — every key playable, but each has
# its own colour. Bach's Well-Tempered Clavier was written for systems like
# this. Cents above C from Werckmeister's "Musikalische Temperatur":
_WERCKMEISTER_CENTS: list[float] = [
    0.0,        # C
    90.225,     # C#
    192.180,    # D
    294.135,    # D#
    390.225,    # E
    498.045,    # F
    588.270,    # F#
    696.090,    # G
    792.180,    # G#
    888.270,    # A
    996.090,    # A#
    1092.180,   # B
]

# Kirnberger III (1779): later well temperament, used by Bach's pupil
# Kirnberger. Pure C–E major third, the syntonic comma distributed across
# the four fifths C–G–D–A–E. Cents above C:
_KIRNBERGER_CENTS: list[float] = [
    0.0,        # C
    90.225,     # C#
    193.157,    # D
    294.135,    # D#
    386.314,    # E   — pure 5:4 like meantone
    498.045,    # F
    590.224,    # F#
    696.578,    # G
    792.180,    # G#
    889.735,    # A
    996.090,    # A#
    1088.269,   # B
]


_CENTS_TABLE: dict[str, list[float]] = {
    "equal":        _EQUAL_CENTS,
    "pythagorean":  _PYTHAGOREAN_CENTS,
    "meantone":     _MEANTONE_CENTS,
    "werckmeister": _WERCKMEISTER_CENTS,
    "kirnberger":   _KIRNBERGER_CENTS,
}


def _just_cents(pitch_class: int) -> float:
    """Convert just-intonation ratio to cents."""
    import math
    return 1200.0 * math.log2(_JUST_RATIOS[pitch_class])


def temper_freq(
    midi_note: int,
    temperament: Temperament = "equal",
    key_root_pc: int = 0,
    a4_hz: float = 440.0,
) -> float:
    """
    Convert a MIDI note to frequency under a given tuning temperament.

    The temperament is anchored to a key root (a pitch class 0-11 where
    0 = C, 1 = C#, ... 9 = A, ... 11 = B). The cents tables are written
    relative to C, so we rotate them so the requested key root maps to
    its equal-temp position.

    For temperaments other than equal, the A4 anchor is preserved: the
    overall scale is shifted so that A4 still sounds at `a4_hz` Hz when
    key_root_pc would otherwise leave A out of place.

    Args:
        midi_note: MIDI note number (0-127). MIDI 60 = middle C.
        temperament: One of equal, just, pythagorean, meantone, werckmeister,
            kirnberger.
        key_root_pc: Pitch class of the tonic (0=C, 2=D, 4=E, 7=G, 9=A, etc.).
            Has no effect for equal temperament.
        a4_hz: Reference pitch for A4 (default 440 Hz).

    Returns:
        Frequency in Hz.

    Examples:
        >>> round(temper_freq(69, "equal"), 2)
        440.0
        >>> # Pythagorean E in C major: 81/64 above C, so brighter than equal
        >>> temper_freq(64, "pythagorean", 0) > temper_freq(64, "equal")
        True
    """
    if midi_note <= 0:
        return 0.0

    if temperament == "equal":
        return a4_hz * (2.0 ** ((midi_note - 69) / 12.0))

    # Resolve cents table (just intonation is computed on the fly).
    if temperament == "just":
        cents_from_c = [_just_cents(i) for i in range(12)]
    else:
        if temperament not in _CENTS_TABLE:
            raise ValueError(
                f"Unknown temperament '{temperament}'. "
                f"Valid: equal, just, pythagorean, meantone, werckmeister, kirnberger"
            )
        cents_from_c = _CENTS_TABLE[temperament]

    # Rotate the table so that key_root_pc becomes the new "0" position.
    # The interval from the new tonic to each pitch class is the same shape,
    # just starting at a different chromatic step.
    rotated: list[float] = [0.0] * 12
    for pc in range(12):
        # Cents from new tonic to pitch class `pc`
        idx = (pc - key_root_pc) % 12
        # cents_from_c is the shape rooted at C; we want the same shape rooted
        # at key_root_pc. So position (key_root_pc + i) gets cents_from_c[i].
        # Equivalently: rotated[(key_root_pc + i) % 12] = cents_from_c[i].
        pass
    for i in range(12):
        rotated[(key_root_pc + i) % 12] = cents_from_c[i]

    pitch_class = midi_note % 12
    octave = midi_note // 12

    # Cents above C0 in the chosen temperament.
    # We treat the rotated table's index 0 as the C of each octave so that
    # frequencies map smoothly across octave boundaries.
    cents_above_c0 = rotated[pitch_class] + (octave * 1200.0)

    # Equal temperament cents-above-C0 for the A4 anchor (MIDI 69).
    a4_cents_equal = (69 % 12) * 100.0 + (69 // 12) * 1200.0  # 6900
    # And cents-above-C0 for A4 in the rotated tempered table.
    a4_cents_tempered = rotated[9] + (69 // 12) * 1200.0

    # Hz of C0 such that A4 in this temperament still equals a4_hz.
    # f = a4_hz * 2^((cents - a4_cents_tempered) / 1200)
    return a4_hz * (2.0 ** ((cents_above_c0 - a4_cents_tempered) / 1200.0))


def list_temperaments() -> list[str]:
    """Return all supported temperament names."""
    return ["equal", "just", "pythagorean", "meantone", "werckmeister", "kirnberger"]


def temperament_description(name: str) -> str:
    """Return a one-line human-readable description of a temperament."""
    descriptions = {
        "equal": "12-TET — modern standard, every semitone identical (100¢).",
        "just": "5-limit just intonation — pure harmonic ratios from the tonic.",
        "pythagorean": "Stacked perfect fifths (3:2) — bright thirds, one wolf fifth.",
        "meantone": "1/4-comma meantone (c. 1500-1700) — pure major thirds.",
        "werckmeister": "Werckmeister III (1691) — well temperament for J.S. Bach.",
        "kirnberger": "Kirnberger III (1779) — well temperament with pure C-E third.",
    }
    return descriptions.get(name, f"Unknown temperament: {name}")
